apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: vijaym1999/waterproofing-chatbot:7c4dbdc3edc73074e8983df8c9881d634852497b
          ports:
            - containerPort: 8000
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: chatbot-service
            - name: DD_ENV
              value: prod
            - name: DD_VERSION
              value: v1
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

