apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vijaym1999/waterproofing-frontend:6cd5d01d1bd8a21cd31f396c4256a6a49c33a651
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
