apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vijaym1999/waterproofing-backend:3a6b241c1a20dad434f748e30b5c13c4a8422b71
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD

        - name: APPINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=46e60640-562a-4bbf-834e-4717fae9dcc9;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=dd18984f-30d2-4dca-aee4-2cd4b462d8c6"
