apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: waterproof
data:
  DB_HOST: postgres
  DB_NAME: waterproofing
  DB_USER: postgres   
  CHATBOT_SERVICE_URL: http://chatbot-service.chatbot.svc.cluster.local:8000
