apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: waterproof
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vijaym1999/waterproofing-frontend:f856ef6ff411c9fc0542984b40bf1762d5c438be
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
