apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: waterproof
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vijaym1999/waterproofing-frontend:1856178a52a635962830a34c720b3f7630d7d8d1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
