apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: waterproof
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vijaym1999/waterproofing-frontend:6c6e8eb2b8c09fe1831599632cbd0f3d45a769c7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
