name: CI - Build, Push, Update Manifests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'   # prevents infinite loop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout
      uses: actions/checkout@v3

    # 2️⃣ Set image tag
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    # 3️⃣ Login to DockerHub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 4️⃣ Build & Push Backend
    - name: Build Backend
      run: |
        docker build -t vijaym1999/waterproofing-backend:${IMAGE_TAG} ./backend
        docker push vijaym1999/waterproofing-backend:${IMAGE_TAG}

    # 5️⃣ Build & Push Frontend
    - name: Build Frontend
      run: |
        docker build -t vijaym1999/waterproofing-frontend:${IMAGE_TAG} ./frontend
        docker push vijaym1999/waterproofing-frontend:${IMAGE_TAG}

    # 6️⃣ Update Kubernetes YAML (VERY IMPORTANT)
    - name: Update manifests
      run: |
        sed -i "s|image: vijaym1999/waterproofing-backend:.*|image: vijaym1999/waterproofing-backend:${IMAGE_TAG}|g" k8s/base/backend-deployment.yaml
        sed -i "s|image: vijaym1999/waterproofing-frontend:.*|image: vijaym1999/waterproofing-frontend:${IMAGE_TAG}|g" k8s/base/frontend-deployment.yaml

    # 7️⃣ Commit & Push changes
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "update image tag to ${IMAGE_TAG}" || echo "No changes"
        git push
